language: python
addons:
  postgresql: "9.3"
dist: trusty
sudo: required
services:
  postgresql

python:
  - "2.7"
before_install:
  - sudo apt-get -y update
install:
  - pip install fiona
  - sudo apt-get -y install python-dev build-essential python-dbus python-gst0.10
  - psql -c "create role round superuser login;"  -U postgres
  - psql -c "create database roundware;" -U postgres
  - psql -c "grant all on database roundware to round;"  -U postgres
  - psql -c "alter user round password 'round';"  -U postgres
  - psql roundware -c "create extension postgis;" -U postgres
  - pip install -r requirements/dev.txt
  - sudo apt-get install --reinstall python-setuptools
before_script:
# Setup Roundware log file.
  - sudo touch /var/log/roundware
  - sudo chmod 777 /var/log/roundware
# Setup rwmedia directory for mock files.
  - sudo mkdir /var/www
  - sudo chmod 777 /var/www
  - export PYTHONPATH=.:/usr/lib/python2.7/dist-packages/
script: python roundware/manage.py test --settings=roundware.settings.testing