language: python
addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-9.3-postgis-2.3
      - python-dev
      - build-essential
      - python-dbus
      - python-gst0.10
      - python-setuptools

dist: trusty
sudo: required

python:
  - "2.7"

before_install:
  - sudo apt-get -y update

install:
  - pip install setuptools pip --upgrade
  - easy_install distribute
  - pip install distribute --upgrade
  - pip install -r requirements/dev.txt --upgrade

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3

  - psql -c "create role round superuser login;"  -U postgres
  - psql -c "create database roundware;" -U postgres
  - psql -c "grant all on database roundware to round;"  -U postgres
  - psql -c "alter user round password 'round';"  -U postgres
  - psql roundware -c "create extension postgis;" -U postgres

# Setup Roundware log file.
  - sudo touch /var/log/roundware
  - sudo chmod 777 /var/log/roundware
# Setup rwmedia directory for mock files.
  - sudo mkdir /var/www
  - sudo chmod 777 /var/www


script: python roundware/manage.py test --settings=roundware.settings.testing