version: "3"
services:
  roundware-db:
    image: mdillon/postgis:10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: round
      POSTGRES_PASSWORD: round
    ports:
      - "5432"
  roundware:
    build: "."
    image: roundware:latest
    ports:
      - "8000:8000"
    command: bash -c "
       python3 roundware/manage.py migrate &&
       python3 roundware/manage.py runserver 0.0.0.0:8000
      "
    environment:
      ROUNDWARE_DEBUG: "true"
      ROUNDWARE_DB_HOST: "roundware-db"
      ROUNDWARE_DB_NAME: "round"
    volumes:
      - .:/code
      - logs:/roundware/logs
    depends_on:
      - roundware-db

volumes:
  logs: